// <auto-generated />
using FreePro.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FreePro.API.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("FreePro.API.Model.Meeting", b =>
                {
                    b.Property<int>("MeetingId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Batch");

                    b.Property<int>("Invited");

                    b.Property<string>("MeetingDate");

                    b.Property<string>("Place");

                    b.Property<string>("Theme");

                    b.HasKey("MeetingId");

                    b.ToTable("Meetings");
                });
#pragma warning restore 612, 618
        }
    }
}
